server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news_app
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: off
    hibernate:
      ddl-auto: update
    show-sql: true

