server:
  port: 8088


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news_app
    username: ${POSTGRES_USERNAME:blablausername}
    password: ${POSTGRES_PASSWORD:blablapasswrod}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: off
    hibernate:
      ddl-auto: none
    show-sql: true

cron:
  mail-sender:
    schedule-time: ${CRON_MAIL_SENDER:0-59 * * * * *}
  reply-notification:
    schedule-time-mail-send: ${CRON_NOTIFICATION_SENDER:0/1 * * * * *}
